packageExtensions:
  "@nomiclabs/ethereumjs-vm@*":
    dependencies:
      "bn.js": "*"
      "rlp": "*"
  "ethereumjs-blockchain@*":
    dependencies:
      "bn.js": "*"

yarnPath: ".yarn/releases/yarn-berry.cjs"