packageExtensions:
  "@nomiclabs/ethereumjs-vm@*":
    dependencies:
      "bn.js": "*"
      "rlp": "*"
  "ethereumjs-blockchain@*":
    dependencies:
      "bn.js": "*"
  "util.promisify@*":
    dependencies: 
      "has-symbols": "*"

yarnPath: ".yarn/releases/yarn-berry.cjs"